include: package:flutter_lints/flutter.yaml

# Specify analysis options.
#
# Until there are meta linter rules, each desired lint must be explicitly enabled.
# See: https://github.com/dart-lang/linter/issues/288
#
# For a list of lints, see: http://dart-lang.github.io/linter/lints/
# See the configuration guide for more
# https://github.com/dart-lang/sdk/tree/master/pkg/analyzer#configuring-the-analyzer

analyzer:
  exclude:
    - lib/**/*.pb*.dart
    - lib/**/*.g.dart
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore

linter:
  rules:
    unnecessary_breaks: true
    prefer_single_quotes: true
    constant_identifier_names: true
    prefer_final_fields: true
    prefer_mixin: false
    avoid_function_literals_in_foreach_calls: false
    avoid_catches_without_on_clauses: false
    # Disabled for Flutter Lints
    avoid_print: false
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    prefer_relative_imports: true
    # allow nodes to override type.
    overridden_fields: false
    implicit_call_tearoffs: false
