name: codelessly_sdk
description: Codelessly CloudUI™ - Server-driven UI for Flutter. Supercharge your Flutter apps with dynamic UI and real-time updates. Build and publish UI without code!
version: 3.0.2
homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslySDK

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  # Codelessly
  codelessly_api: 2.1.0
  codelessly_json_annotation: 4.8.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  firebase_ui_firestore: ^1.6.4
  google_fonts: ^6.2.1

  # Core Flutter
  collection: '>=1.17.0 <2.0.0'
  http: '>=1.1.2 <2.0.0'
  intl: '>=0.17.0 <1.0.0'
  meta: ">=1.9.0 <2.0.0"
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_wkwebview: ^3.14.0
  webview_flutter_web: ^0.2.3+2

  # 3rd Party Core Framework
  equatable: ^2.0.5
  vector_math: ^2.1.4
  provider: ^6.1.2
  uuid: ^4.4.2
  flutter_svg: ^2.0.10+1

  # File and Image
  path: ^1.9.0
  path_provider: ^2.1.4

  # Storage and Caching
  hive_ce_flutter: ^2.0.0

  # JSON
  json_path: ^0.7.4
  rfc_6901: ^0.2.0 # json pointer spec
  jwt_decoder: ^2.0.1

  # Project UI
  flutter_animation_progress_bar: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  codelessly_json_serializable: 6.7.1+1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelessly_logo.png

false_secrets:
  - /lib/src/constants.dart
  - /lib/src/firebase_options_prod.dart

scripts: scripts.yaml
