name: codelessly_sdk
description: Codelessly Cloud UI SDK for Flutter apps.

version: 0.0.2

homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslySDK
issue_tracker: https://github.com/Codelessly/CodelesslySDK/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ">=2.0.5 <3.0.0"
  google_fonts: ^4.0.4
  json_annotation: ^4.8.1
  url_launcher: ">=6.1.11 <7.0.0"
  collection: ">=1.17.0 <2.0.0"
  http: ^0.13.6
  intl: ">=0.18.0 <2.0.0"
  universal_html: ^2.2.2
  webview_flutter: ^4.2.1
  webview_flutter_android: ^3.7.1
  webview_flutter_wkwebview: ^3.4.4
  flutter_animation_progress_bar: ^2.3.1
  cached_network_image: ^3.2.3
  vector_math: ">=2.1.4 <3.0.0"
  grpc: ^3.1.0
  protobuf: ^2.1.0
  fixnum: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
  provider: ^6.0.5
  json_path: 0.5.2
  meta: ">=1.9.0 <2.0.0"
  codelessly_api: ^0.0.2
  # Uncomment to develop locally.
#  codelessly_api:
#    path: ../codelessly_api

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/codelessly_logo.png

false_secrets:
  - /lib/src/constants.dart

scripts: scripts.yaml