name: codelessly_sdk
description: Codelessly CloudUI™ - Supercharge your Flutter apps with dynamic UI and real-time updates. Build and publish UI without code!
version: 0.0.7
homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslySDK

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

platforms:
  android:
  ios:
  linux:
  windows:
  macos:
  web:

dependencies:
  flutter:
    sdk: flutter
  codelessly_api: 0.0.7
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  json_annotation: ^4.8.1
  url_launcher: ^6.1.12
  collection: '>=1.17.0 <2.0.0'
  http: '>=0.13.0 <2.0.0'
  intl: '>=0.17.0 <1.0.0'
  universal_html: ^2.2.3
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.2
  webview_flutter_wkwebview: ^3.7.2
  flutter_animation_progress_bar: ^2.3.1
  vector_math: ^2.1.4
  grpc: ^3.2.3
  protobuf: ^3.0.0
  fixnum: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
  provider: ^6.0.5
  json_path: ^0.6.2
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/codelessly_logo.png

false_secrets:
  - /lib/src/constants.dart

scripts: scripts.yaml
