name: codelessly_sdk
description: Codelessly CloudUI™ - Supercharge your Flutter apps with dynamic UI and real-time updates. Build and publish UI without code!
version: 1.7.0
homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslySDK

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:

dependencies:
  flutter:
    sdk: flutter
  codelessly_api: 1.7.0
  codelessly_json_annotation: 4.8.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_ui_firestore: ^1.6.2
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  collection: '>=1.17.0 <2.0.0'
  http: '>=1.1.2 <2.0.0'
  intl: '>=0.17.0 <1.0.0'
  universal_html: ^2.2.4
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  webview_flutter_web: ^0.2.2+4
  flutter_animation_progress_bar: ^2.3.1
  vector_math: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  json_path: ^0.7.1
  meta: ">=1.9.0 <2.0.0"
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  rfc_6901: ^0.2.0 # json pointer spec

dev_dependencies:
  flutter_test:
    sdk: flutter
  codelessly_json_serializable: 6.7.1+1
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/codelessly_logo.png

false_secrets:
  - /lib/src/constants.dart
  - /lib/src/firebase_options_prod.dart

scripts: scripts.yaml
