// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR92IoT_1kwBYOLBbPvln48DwaXTeTrxk',
    appId: '1:1008464357540:web:1aee4cb376ddd458a6de31',
    messagingSenderId: '1008464357540',
    projectId: 'codeless-app',
    authDomain: 'codeless-app.firebaseapp.com',
    databaseURL: 'https://codeless-app-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-app.appspot.com',
    measurementId: 'G-E7LRJGTKDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_acaGPk23JdiwqqHqzYgJGSbKPP7bXI',
    appId: '1:1008464357540:android:a67369aaaae42a92a6de31',
    messagingSenderId: '1008464357540',
    projectId: 'codeless-app',
    databaseURL: 'https://codeless-app-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehrT8nR7iJHtANJAA3AZi_SwCN1Z2ryU',
    appId: '1:1008464357540:ios:17b5c319b8ec753aa6de31',
    messagingSenderId: '1008464357540',
    projectId: 'codeless-app',
    databaseURL: 'https://codeless-app-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-app.appspot.com',
    iosClientId:
        '1008464357540-quq84tmv8e0b7qo3jo2r3148pd9snfni.apps.googleusercontent.com',
    iosBundleId: 'com.codelessly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehrT8nR7iJHtANJAA3AZi_SwCN1Z2ryU',
    appId: '1:1008464357540:ios:17b5c319b8ec753aa6de31',
    messagingSenderId: '1008464357540',
    projectId: 'codeless-app',
    databaseURL: 'https://codeless-app-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-app.appspot.com',
    iosClientId:
        '1008464357540-quq84tmv8e0b7qo3jo2r3148pd9snfni.apps.googleusercontent.com',
    iosBundleId: 'com.codelessly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR92IoT_1kwBYOLBbPvln48DwaXTeTrxk',
    appId: '1:1008464357540:web:ed36d3c5f17fe57ea6de31',
    messagingSenderId: '1008464357540',
    projectId: 'codeless-app',
    authDomain: 'codeless-app.firebaseapp.com',
    databaseURL: 'https://codeless-app-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-app.appspot.com',
    measurementId: 'G-4ZDTJ4YDM0',
  );
}
