// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-blUIZe_brP4D8xsjo2TcUPF-FDQLGs',
    appId: '1:950033523579:web:3e5cdf769ebfea4f1353de',
    messagingSenderId: '950033523579',
    projectId: 'codeless-dev',
    authDomain: 'codeless-dev.firebaseapp.com',
    databaseURL: 'https://codeless-dev-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-dev.appspot.com',
    measurementId: 'G-L2ZRGNVW65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BnLJa8OlPY6G0WB4IUA6ZPpJ9UDq0CM',
    appId: '1:950033523579:android:71365ba75872617a1353de',
    messagingSenderId: '950033523579',
    projectId: 'codeless-dev',
    databaseURL: 'https://codeless-dev-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxDINPf_Iv7JijcNurimH9Qc5sshuI8dU',
    appId: '1:950033523579:ios:4b2bc5b87231ea991353de',
    messagingSenderId: '950033523579',
    projectId: 'codeless-dev',
    databaseURL: 'https://codeless-dev-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-dev.appspot.com',
    androidClientId:
        '950033523579-5o82dsg72jv51i9slcj2q1q61c6es41f.apps.googleusercontent.com',
    iosClientId:
        '950033523579-6apd2e5cn1l192dqr02lovnmonsnuvdc.apps.googleusercontent.com',
    iosBundleId: 'com.codelessly.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxDINPf_Iv7JijcNurimH9Qc5sshuI8dU',
    appId: '1:950033523579:ios:4b2bc5b87231ea991353de',
    messagingSenderId: '950033523579',
    projectId: 'codeless-dev',
    databaseURL: 'https://codeless-dev-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-dev.appspot.com',
    androidClientId:
        '950033523579-5o82dsg72jv51i9slcj2q1q61c6es41f.apps.googleusercontent.com',
    iosClientId:
        '950033523579-6apd2e5cn1l192dqr02lovnmonsnuvdc.apps.googleusercontent.com',
    iosBundleId: 'com.codelessly.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTTUFm_7a_XYJxbtanhbiqV6Qx1le8XGw',
    appId: '1:950033523579:web:43049f1d3286e7ec1353de',
    messagingSenderId: '950033523579',
    projectId: 'codeless-dev',
    authDomain: 'codeless-dev.firebaseapp.com',
    databaseURL: 'https://codeless-dev-default-rtdb.firebaseio.com',
    storageBucket: 'codeless-dev.appspot.com',
    measurementId: 'G-DNVPDM6CLB',
  );
}
